/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-tint": "#565e74",
        "surface-container-low": "#f2f4f6",
        "surface": "#f7f9fb",
        "on-primary-fixed": "#131b2e",
        "outline-variant": "#c6c6cd",
        "on-primary": "#ffffff",
        "surface-dim": "#d8dadc",
        "surface-container-high": "#e6e8ea",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed-dim": "#6bd8cb",
        "electric-blue": "#2563EB",
        "on-error-container": "#93000a",
        "primary": "#000000",
        "on-tertiary-container": "#0c9488",
        "primary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#adc6ff",
        "secondary-container": "#2170e4",
        "on-surface-variant": "#45464d",
        "on-secondary-fixed-variant": "#004395",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "outline": "#76777d",
        "on-error": "#ffffff",
        "tertiary": "#000000",
        "inverse-surface": "#2d3133",
        "inverse-primary": "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        "secondary-fixed": "#d8e2ff",
        "on-tertiary-fixed-variant": "#005049",
        "surface-variant": "#e0e3e5",
        "charcoal-dark": "#1E293B",
        "slate-gray": "#64748B",
        "surface-container-highest": "#e0e3e5",
        "error": "#ba1a1a",
        "primary-container": "#131b2e",
        "secondary": "#0058be",
        "on-secondary-fixed": "#001a42",
        "on-secondary-container": "#fefcff",
        "primary-fixed-dim": "#bec6e0",
        "surface-bright": "#f7f9fb",
        "on-background": "#191c1e",
        "on-tertiary-fixed": "#00201d",
        "border-subtle": "#E2E8F0",
        "teal-accent": "#14B8A6",
        "on-primary-container": "#7c839b",
        "background": "#f7f9fb",
        "surface-container": "#eceef0",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "tertiary-container": "#00201d",
        "on-surface": "#191c1e",
        "tertiary-fixed": "#89f5e7"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "rail-width": "300px",
        "sidebar-width": "260px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "margin-page": "32px",
        "gutter": "24px",
        "stack-lg": "24px",
        "container-max": "1280px"
      },
      "fontFamily": {
        "body-lg": ["Inter", "sans-serif"],
        "meta-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "meta-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-md": ["13px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-sm": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
